---
- name: jenkins installation
  hosts: all
  remote_user: root
  tasks:
    - name: update the system packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: java installation
      apt:
        name: default-jdk
    - name: add the repo
      apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
    - name: config repo
      apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present
    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes
    - name: ensure jenkins is running
      service: name=jenkins state=started
